// src/lib/RateSelector.svelte
<script lang="ts">
  import { rate, setRate } from "../stores/rateStore"; // Assumendo che il file sia qui

  /**
   * Gestore per l'evento 'change' del tag <select>.
   * La sintassi '$rate' è la comodità di Svelte per leggere il valore dello store.
   */
  function handleRateChange(event: Event): void {
    const selectedValue = (event.target as HTMLSelectElement).value;
    setRate(selectedValue);
  }
</script>

<div class="form-floating">
  <select
    id="rate_selector"
    class="form-control"
    value={$rate.name}
    on:change={handleRateChange}
  >
    <option>F2</option>
    <option>F3</option>
  </select>
  <label for="rate_selector">Rate selector</label>
</div>

// src/components/RateSelector.vue
<script setup lang="ts">
import { useRate } from '../composables/rates';

const { rate, setRate } = useRate();
</script>

<template>
  <div class="form-floating">
    <select id="rate_selector" class="form-control" :value="rate.name"
      @change="event => setRate((event.target as HTMLSelectElement).value)">
      <option>F2</option>
      <option>F3</option>
    </select>
    <label for="rate_selector">Rate selector</label>
  </div>
</template>
